### ISSUE TITLE
[Bug] azure-configuration branch is missing

### ISSUE THREAD

**Issue by alextitov1** [skills/continuous-delivery-azure#11]
**Describe the bug**
Workflow "Check step 2, Set up the Azure environment" fails at the job. `Create azure-configuration pull request` with a error:
```
pull request create failed: GraphQL: Head sha can't be blank, Base sha can't be blank, No commits between main and azure-configuration, Head ref must be a branch (createPullRequest)
Error: Process completed with exit code 1.
```
**To Reproduce**
Follow Readme.md guide at the step 2.16 commit checks will fail and you will not be able to proceed the course. 

**Additional context**
at this step workflow should create a PR from azure-configuration branch which is currently missing in the this template

**Comment by markpatterson27** [comment]
See the discussion board for more on this: https://github.com/orgs/skills/discussions/14

It's not that the branch is missing. There is a missing yaml file (`spinup-destroy.yml`) and a missing commit of that file to the `azure-configuration` branch. This means that the head and base refs point to the same commit when trying to create the PR. That will throw the error you got because you can't create a PR with no commits in it. There must be a difference in history between HEAD and base refs.

I think everyone is waiting for the Skills team to take another look at this lab, because there are a number of issues with it that need to be fixed (See [dicussion thread about it](https://github.com/orgs/skills/discussions/14).)

**Comment by vipwlb** [comment]
Thanks for the information, is there any timeline for the bug fix? Thanks！

**Comment by brntbeer** [comment]
@heiskr / @emilyistoofunky any thoughts about this ?

**Comment by heiskr** [comment]
We're open to pull requests. I believe a contractor ported this course from a previous Learning Lab version:

- https://github.com/githubtraining/continuous-delivery-azure
- https://github.com/githubtraining/continuous-delivery-azure-template

**Comment by heiskr** [comment]
I'll need to defer to @skills/skills-content-reviewers for questions on course content.

**Comment by sgar5067** [comment]
We're now in December. Any chance this lab will be corrected anytime soon?

**Comment by VladimirTitkovEpam** [comment]
Any updates?

**Comment by sgould420** [comment]
This exercise should be removed from the learning path at [https://learn.microsoft.com/en-us/training/modules/github-actions-cd/3-create-workflow-deploy-azure](url)
until it is fixed.

**Comment by heiskr** [comment]
Thank you for opening this issue. I'm closing this issue out per https://github.com/skills/continuous-delivery-azure/pull/20#issuecomment-1445303419

The GitHub Skills folks don't control or influence the content on Microsoft Learn, just fyi.
